"""Deterministic project-scaffold renderer (no LLM).

Renders the repo-root boilerplate a generated project needs (Dockerfile, .gitignore, README.md,
docker-compose.yml, .env.example, requirements.txt, package.json) once per run, before any work
item is generated — so the LLM is never asked to produce files whose shape is already known. Most
files come from the Jinja2 templates in ``app/templates/``; the ``README.md`` is instead built by
:mod:`app.services.readme`, which mines the Design Package to emit a real, application-specific
README (features, tech stack, project structure, API, screens, data model) rather than a stub.

INPUT-AWARE, not stack-aware. Two levels of input-drivenness:

  1. WHICH files are emitted — a disabled capability contributes NO file at all (see ``_SCAFFOLD``).
  2. WHAT they contain — REAL application values from the Design Package (name, description,
     version, the actual dependency lists, scripts, and env-var names) flow into the templates.
     Not placeholders: the ``{{ }}`` live only in the ``.j2`` recipes; the rendered output carries
     concrete values pulled from the package.

Absent a capabilities artifact, ``DEFAULT_CAPABILITIES`` reproduces the legacy FastAPI+React full
scaffold, so existing runs keep working. New capabilities/values are plain data — no redesign.

JSON files are rendered through Jinja's ``| tojson`` filter (never hand-built braces), so the
output is valid JSON for ANY data — no trailing-comma or escaping bugs.

Same family as ``plan_builder.py`` / ``manifest_gate.py``: pure logic, deterministic, no LLM, no
side effects beyond returning content (the caller — ``scaffold_node`` — writes it via the executor).
"""

from __future__ import annotations

import copy
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

from jinja2 import Environment, FileSystemLoader

try:  # PyYAML is available in this service; fall back gracefully if a slim env drops it.
    import yaml
except ModuleNotFoundError:  # pragma: no cover
    yaml = None  # type: ignore[assignment]

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"

# Legacy defaults: the full FastAPI + React/Vite stack with every capability ON. Resolving a
# Design Package that carries NO capabilities artifact yields exactly this — so pre-existing runs
# still emit the original 7 files. New capabilities/values are added here (or supplied by the
# package); nothing else in the system needs to change.
DEFAULT_CAPABILITIES: dict[str, Any] = {
    "project": {
        "name": "",
        "version": "0.1.0",
        "description": "Generated by the Implementation service from a Design Package.",
    },
    "frontend": {
        "enabled": True,
        "framework": "react",
        "bundler": "vite",
        # Real dependency lists (name -> version). The Design Package can override or extend these.
        "dependencies": {"react": "^18.3.0", "react-dom": "^18.3.0"},
        "devDependencies": {},   # baseline (typescript/bundler/vitest) filled in _normalize
        "scripts": {},           # derived from bundler in _normalize when not supplied
    },
    "backend": {
        "enabled": True,
        "framework": "fastapi",
        "dependencies": {},      # derived from framework + db/auth/testing in _normalize
    },
    "database": {"enabled": True, "provider": "postgres"},
    "authentication": {"enabled": True},
    "docker": {"enabled": True},
    "environment": {"enabled": True, "variables": []},  # derived from db/auth in _normalize
    "testing": {"enabled": True},
}

# Framework/feature -> real dependency specs. Data, not code: adding Flask/Prisma/etc. is a table
# edit here, not a rewrite. Specs are pip-style for the backend (rendered into requirements.txt).
_BACKEND_DEPS_BY_FRAMEWORK: dict[str, dict[str, str]] = {
    "fastapi": {"fastapi": ">=0.115,<1.0", "uvicorn[standard]": ">=0.32,<1.0", "pydantic": ">=2.9,<3.0"},
    "flask": {"flask": ">=3.0,<4.0", "gunicorn": ">=23.0,<24.0"},
}
_BACKEND_DB_DEPS: dict[str, dict[str, str]] = {
    "postgres": {"sqlalchemy": ">=2.0,<3.0", "psycopg[binary]": ">=3.2,<4.0"},
    "_default": {"sqlalchemy": ">=2.0,<3.0"},
}
_BACKEND_AUTH_DEPS = {"python-jose[cryptography]": ">=3.3,<4.0", "passlib[bcrypt]": ">=1.7,<2.0"}
_BACKEND_TEST_DEPS = {"pytest": ">=8.3,<9.0", "httpx": ">=0.27,<1.0"}


@dataclass(frozen=True)
class ScaffoldConfig:
    """Normalized, immutable capabilities view that drives what the scaffold emits.

    Held as a nested ``data`` dict rather than fixed fields so adding a capability/value is additive
    data, not a schema change. ``enabled()`` is the single predicate used by both the file manifest
    (``_SCAFFOLD``) and the templates' context.
    """

    data: dict[str, Any]

    def enabled(self, section: str) -> bool:
        """True if ``section`` is turned on. Accepts ``{enabled: bool}`` or a bare bool value."""
        node = self.data.get(section)
        if isinstance(node, dict):
            return bool(node.get("enabled", False))
        return bool(node)

    def option(self, section: str, key: str, default: Any = None) -> Any:
        node = self.data.get(section)
        return node.get(key, default) if isinstance(node, dict) else default

    @property
    def project_name(self) -> str:
        return self.option("project", "name", "") or "project"


# (template filename, rendered output path, predicate). A file is emitted ONLY if predicate(cfg)
# is True — skipping happens here, at manifest-filter time, so a disabled capability yields no file
# at all rather than an empty/whitespace one. Order = the order files are written and logged.
# ``README.md`` uses the ``_README`` sentinel: it is not a Jinja template but is built by
# app.services.readme.render_readme (a real, per-application README, not a stub).
_README = "<readme>"
_SCAFFOLD: list[tuple[str, str, Callable[[ScaffoldConfig], bool]]] = [
    ("Dockerfile.j2", "Dockerfile", lambda c: c.enabled("docker") and c.enabled("backend")),
    ("gitignore.j2", ".gitignore", lambda c: True),
    (_README, "README.md", lambda c: True),
    ("docker-compose.yml.j2", "docker-compose.yml", lambda c: c.enabled("docker")),
    ("env.example.j2", ".env.example", lambda c: c.enabled("environment")),
    ("requirements.txt.j2", "requirements.txt", lambda c: c.enabled("backend")),
    ("package.json.j2", "package.json", lambda c: c.enabled("frontend")),
]

# Design Package keys under which a capabilities config may travel (case-insensitive).
_CAPABILITY_ARTIFACT_NAMES = (
    "capabilities",
    "capabilities.yaml",
    "capabilities.yml",
    "capabilities.json",
    "scaffold.json",
)


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge ``override`` onto a deep copy of ``base`` (override wins). Deterministic."""
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def _parse_capabilities(raw: Any) -> dict[str, Any]:
    """Coerce a capabilities artifact to a dict.

    Accepts an already-parsed dict (``.json`` packs), a JSON string, or a YAML string (``.yaml``
    packs arrive as text). Anything unparseable falls back to ``{}`` (→ defaults only).
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw.strip():
        try:
            loaded = json.loads(raw)
            return loaded if isinstance(loaded, dict) else {}
        except json.JSONDecodeError:
            pass
        if yaml is not None:
            try:
                loaded = yaml.safe_load(raw)
                return loaded if isinstance(loaded, dict) else {}
            except yaml.YAMLError:
                pass
    return {}


def _lookup(design_package: dict[str, Any], *names: str) -> Any:
    """First present artifact among ``names`` (case-insensitive). Mirrors code_generator._artifact."""
    lowered = {k.lower(): v for k, v in design_package.items()}
    for name in names:
        if name in design_package:
            return design_package[name]
        if name.lower() in lowered:
            return lowered[name.lower()]
    return None


def _enabled(cfg: dict[str, Any], section: str) -> bool:
    node = cfg.get(section)
    return bool(node.get("enabled")) if isinstance(node, dict) else bool(node)


def _normalize(cfg: dict[str, Any], project_id: str) -> dict[str, Any]:
    """Fill the REAL application values Jinja will interpolate, deriving sensible ones when the
    Design Package didn't state them. Deterministic; explicit package values always win.

    - project.name/version/description
    - frontend.devDependencies (typescript + bundler + vitest) and frontend.scripts (dev/build/test)
    - backend.dependencies (framework baseline + db/auth/testing extras + explicit)
    - environment.variables (from db/auth flags when not given)
    """
    testing_on = _enabled(cfg, "testing")

    project = cfg.setdefault("project", {})
    if not project.get("name"):
        project["name"] = project_id or "project"
    project.setdefault("version", "0.1.0")
    project.setdefault("description", "Generated by the Implementation service from a Design Package.")

    fe = cfg.setdefault("frontend", {})
    bundler = fe.setdefault("bundler", "vite")
    fe.setdefault("framework", "react")
    fe.setdefault("dependencies", {"react": "^18.3.0", "react-dom": "^18.3.0"})
    dev = dict(fe.get("devDependencies") or {})
    dev.setdefault("typescript", "^5.6.0")
    dev.setdefault(bundler, "^5.4.0")
    if testing_on:
        dev.setdefault("vitest", "^2.1.0")
    fe["devDependencies"] = dev
    if not fe.get("scripts"):
        scripts = {"dev": bundler, "build": f"tsc && {bundler} build"}
        if testing_on:
            scripts["test"] = "vitest"
        fe["scripts"] = scripts

    be = cfg.setdefault("backend", {})
    framework = be.setdefault("framework", "fastapi")
    deps = dict(_BACKEND_DEPS_BY_FRAMEWORK.get(framework, _BACKEND_DEPS_BY_FRAMEWORK["fastapi"]))
    if _enabled(cfg, "database"):
        provider = cfg.get("database", {}).get("provider", "")
        deps.update(_BACKEND_DB_DEPS.get(provider, _BACKEND_DB_DEPS["_default"]))
    if _enabled(cfg, "authentication"):
        deps.update(_BACKEND_AUTH_DEPS)
    if testing_on:
        deps.update(_BACKEND_TEST_DEPS)
    deps.update(be.get("dependencies") or {})  # explicit package deps win / extend
    be["dependencies"] = deps

    env = cfg.setdefault("environment", {})
    if not env.get("variables"):
        variables: list[str] = []
        if _enabled(cfg, "database"):
            variables.append("DATABASE_URL")
        if _enabled(cfg, "authentication"):
            variables.append("SECRET_KEY")
        env["variables"] = variables

    return cfg


def resolve_scaffold_config(
    project_id: str, design_package: dict[str, Any] | None = None
) -> ScaffoldConfig:
    """Resolve the effective capabilities+values: DEFAULTS ← package capabilities ← derived normal.

    - Starts from ``DEFAULT_CAPABILITIES`` (legacy full stack) so a package with no capabilities
      artifact reproduces the prior behavior.
    - Deep-merges a capabilities artifact from the Design Package when present (see
      ``_CAPABILITY_ARTIFACT_NAMES``); the artifact wins per key.
    - ``_normalize`` fills the real application values (deps/scripts/env/…) Jinja interpolates.
    """
    package = design_package or {}
    raw = _lookup(package, *_CAPABILITY_ARTIFACT_NAMES)
    merged = _deep_merge(DEFAULT_CAPABILITIES, _parse_capabilities(raw))
    return ScaffoldConfig(_normalize(merged, project_id))


def render_scaffold(
    project_id: str, design_package: dict[str, Any] | None = None
) -> list[dict[str, str]]:
    """Render the capability-appropriate repo-root boilerplate for this project.

    Deterministic: the same ``(project_id, design_package)`` always renders the same files and
    contents (no timestamps, no randomness), matching the codegen prompt's determinism rule. A
    disabled capability contributes NO entry to the returned list (clean skip, not an empty file).
    The rendered files carry REAL values from the Design Package, not placeholders.

    Backward compatible: called with just a ``project_id`` (no design package), it resolves to the
    legacy FastAPI+React defaults and emits the original 7 files.
    """
    config = resolve_scaffold_config(project_id, design_package)
    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATES_DIR)),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    # Plain-JSON filter for rendering real values into JSON files. Unlike Jinja's built-in
    # ``tojson`` it does NOT HTML-escape (& < > '), so "tsc && vite build" stays readable, while
    # still guaranteeing valid, correctly-quoted/escaped JSON for any data. Deterministic
    # (insertion order preserved, no sort).
    env.filters["to_json"] = lambda value, indent=2: json.dumps(value, indent=indent, ensure_ascii=False)
    context = {
        "project_id": config.project_name,  # back-compat: templates historically used project_id
        **config.data,
    }
    # Imported here (not at module top) to avoid an import cycle: readme.py type-checks against
    # ScaffoldConfig defined in this module.
    from app.services.readme import render_readme

    entries: list[dict[str, str]] = []
    for template_name, out_path, predicate in _SCAFFOLD:
        if not predicate(config):
            continue
        if template_name == _README:
            content = render_readme(config, design_package)
        else:
            content = env.get_template(template_name).render(**context)
        entries.append({"path": out_path, "content": content})
    return entries
