-- Generated by schema_generator
-- dialect: postgresql

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()

CREATE TABLE users (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    email varchar(320) NOT NULL NOT NULL,
    password_hash varchar(255),
    full_name varchar(255),
    phone varchar(30),
    is_guest_converted boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE roles (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name varchar(100) NOT NULL NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE user_roles (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid NOT NULL NOT NULL,
    role_id uuid NOT NULL NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (user_id, role_id)
);

CREATE TABLE addresses (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid,
    full_name varchar(255) NOT NULL NOT NULL,
    line1 varchar(255) NOT NULL NOT NULL,
    line2 varchar(255),
    city varchar(100) NOT NULL NOT NULL,
    state varchar(100) NOT NULL NOT NULL,
    pin_code varchar(20) NOT NULL NOT NULL,
    country varchar(100) NOT NULL DEFAULT 'India',
    phone varchar(30),
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE serviceable_pin_codes (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    pin_code varchar(20) NOT NULL NOT NULL,
    city varchar(100),
    state varchar(100),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (pin_code)
);

CREATE TABLE categories (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    parent_id uuid,
    name varchar(255) NOT NULL NOT NULL,
    slug varchar(255) NOT NULL NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (slug)
);

CREATE TABLE brands (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name varchar(255) NOT NULL NOT NULL,
    slug varchar(255) NOT NULL NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (slug)
);

CREATE TABLE products (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    category_id uuid,
    brand_id uuid,
    name varchar(255) NOT NULL NOT NULL,
    slug varchar(255) NOT NULL NOT NULL,
    description text,
    base_price_paise bigint NOT NULL NOT NULL,
    tax_rate_percent numeric(5,2) NOT NULL DEFAULT 0.00,
    attributes jsonb,
    average_rating numeric(3,2),
    review_count integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    is_returnable boolean NOT NULL DEFAULT true,
    return_window_days integer NOT NULL DEFAULT 7,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (slug),
    CHECK (base_price_paise >= 0),
    CHECK (tax_rate_percent >= 0),
    CHECK (review_count >= 0),
    CHECK (return_window_days >= 0)
);

CREATE TABLE product_images (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id uuid NOT NULL NOT NULL,
    url varchar(2048) NOT NULL NOT NULL,
    alt_text varchar(255),
    sort_order integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE skus (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id uuid NOT NULL NOT NULL,
    sku_code varchar(100) NOT NULL NOT NULL,
    size varchar(50),
    colour varchar(50),
    variant_attributes jsonb,
    price_paise bigint NOT NULL NOT NULL,
    stock_quantity integer NOT NULL DEFAULT 0,
    reserved_quantity integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (sku_code),
    CHECK (stock_quantity >= 0),
    CHECK (reserved_quantity >= 0),
    CHECK (reserved_quantity <= stock_quantity),
    CHECK (price_paise >= 0)
);

CREATE TABLE promo_codes (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code varchar(50) NOT NULL NOT NULL,
    discount_type varchar(20) NOT NULL NOT NULL,
    discount_value numeric(10,2) NOT NULL NOT NULL,
    minimum_order_paise bigint NOT NULL DEFAULT 0,
    max_uses integer,
    used_count integer NOT NULL DEFAULT 0,
    expires_at timestamptz,
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (code),
    CHECK (discount_type IN ('percentage', 'flat')),
    CHECK (discount_value > 0),
    CHECK (minimum_order_paise >= 0),
    CHECK (used_count >= 0),
    CHECK (max_uses IS NULL OR max_uses > 0)
);

CREATE TABLE carts (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid,
    guest_email varchar(320),
    promo_code_id uuid,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (status IN ('active', 'checked_out', 'abandoned')),
    CHECK (user_id IS NOT NULL OR guest_email IS NOT NULL)
);

CREATE TABLE cart_items (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    cart_id uuid NOT NULL NOT NULL,
    sku_id uuid NOT NULL NOT NULL,
    quantity integer NOT NULL NOT NULL,
    unit_price_paise bigint NOT NULL NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (cart_id, sku_id),
    CHECK (quantity > 0),
    CHECK (unit_price_paise >= 0)
);

CREATE TABLE orders (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_number varchar(50) NOT NULL NOT NULL,
    user_id uuid,
    guest_email varchar(320),
    cart_id uuid,
    promo_code_id uuid,
    promo_code_snapshot varchar(50),
    current_status varchar(30) NOT NULL DEFAULT 'pending_payment',
    delivery_address_snapshot jsonb NOT NULL NOT NULL,
    subtotal_paise bigint NOT NULL NOT NULL,
    discount_paise bigint NOT NULL DEFAULT 0,
    shipping_charge_paise bigint NOT NULL DEFAULT 4900,
    tax_paise bigint NOT NULL DEFAULT 0,
    total_paise bigint NOT NULL NOT NULL,
    free_shipping_threshold_paise bigint NOT NULL DEFAULT 79900,
    pin_code varchar(20) NOT NULL NOT NULL,
    is_pin_code_serviceable boolean NOT NULL DEFAULT true,
    cancellation_reason text,
    cancelled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (order_number),
    CHECK (current_status IN ('pending_payment', 'confirmed', 'packed', 'shipped', 'delivered', 'cancelled', 'return_requested', 'return_approved', 'refunded')),
    CHECK (subtotal_paise >= 0),
    CHECK (discount_paise >= 0),
    CHECK (shipping_charge_paise >= 0),
    CHECK (tax_paise >= 0),
    CHECK (total_paise >= 0),
    CHECK (shipping_charge_paise = CASE WHEN (subtotal_paise - discount_paise) >= free_shipping_threshold_paise THEN 0 ELSE shipping_charge_paise END OR current_status = 'pending_payment'),
    CHECK (user_id IS NOT NULL OR guest_email IS NOT NULL)
);

CREATE TABLE order_items (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id uuid NOT NULL NOT NULL,
    sku_id uuid NOT NULL NOT NULL,
    sku_code_snapshot varchar(100) NOT NULL NOT NULL,
    product_name_snapshot varchar(255) NOT NULL NOT NULL,
    variant_snapshot jsonb,
    quantity integer NOT NULL NOT NULL,
    unit_price_paise bigint NOT NULL NOT NULL,
    tax_rate_percent numeric(5,2) NOT NULL DEFAULT 0.00,
    tax_paise bigint NOT NULL DEFAULT 0,
    is_returnable boolean NOT NULL DEFAULT true,
    return_window_days integer NOT NULL DEFAULT 7,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (quantity > 0),
    CHECK (unit_price_paise >= 0),
    CHECK (tax_rate_percent >= 0),
    CHECK (tax_paise >= 0),
    CHECK (return_window_days >= 0)
);

CREATE TABLE order_status_history (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id uuid NOT NULL NOT NULL,
    status varchar(30) NOT NULL NOT NULL,
    notes text,
    changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (status IN ('pending_payment', 'confirmed', 'packed', 'shipped', 'delivered', 'cancelled', 'return_requested', 'return_approved', 'refunded'))
);

CREATE TABLE stock_reservations (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id uuid,
    cart_id uuid,
    sku_id uuid NOT NULL NOT NULL,
    quantity integer NOT NULL NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    expires_at timestamptz NOT NULL NOT NULL,
    released_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (status IN ('active', 'confirmed', 'released', 'expired')),
    CHECK (quantity > 0)
);

CREATE TABLE payment_attempts (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id uuid NOT NULL NOT NULL,
    provider varchar(50) NOT NULL DEFAULT 'mock',
    provider_reference varchar(255),
    amount_paise bigint NOT NULL NOT NULL,
    currency varchar(10) NOT NULL DEFAULT 'INR',
    status varchar(20) NOT NULL DEFAULT 'initiated',
    failure_reason text,
    test_mode boolean NOT NULL DEFAULT true,
    initiated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (status IN ('initiated', 'pending', 'success', 'failed', 'timed_out')),
    CHECK (amount_paise > 0)
);

CREATE TABLE refunds (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id uuid NOT NULL NOT NULL,
    payment_attempt_id uuid,
    amount_paise bigint NOT NULL NOT NULL,
    reason text,
    status varchar(20) NOT NULL DEFAULT 'pending',
    provider_reference varchar(255),
    processed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (status IN ('pending', 'processed', 'failed')),
    CHECK (amount_paise > 0)
);

CREATE TABLE return_requests (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id uuid NOT NULL NOT NULL,
    order_item_id uuid NOT NULL NOT NULL,
    requested_by uuid,
    reason text,
    status varchar(20) NOT NULL DEFAULT 'requested',
    reviewed_by uuid,
    review_notes text,
    reviewed_at timestamptz,
    return_window_expires_at timestamptz NOT NULL NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (status IN ('requested', 'approved', 'rejected', 'completed'))
);

CREATE TABLE order_tracking (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id uuid NOT NULL NOT NULL,
    event_label varchar(100) NOT NULL NOT NULL,
    event_description text,
    location varchar(255),
    occurred_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE notifications (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid,
    guest_email varchar(320),
    type varchar(50) NOT NULL NOT NULL,
    title varchar(255) NOT NULL NOT NULL,
    body text,
    payload jsonb,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (user_id IS NOT NULL OR guest_email IS NOT NULL)
);

-- Foreign keys
ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT;
ALTER TABLE addresses ADD CONSTRAINT fk_addresses_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE categories ADD CONSTRAINT fk_categories_parent_id FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL;
ALTER TABLE products ADD CONSTRAINT fk_products_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL;
ALTER TABLE products ADD CONSTRAINT fk_products_brand_id FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE SET NULL;
ALTER TABLE product_images ADD CONSTRAINT fk_product_images_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE;
ALTER TABLE skus ADD CONSTRAINT fk_skus_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT;
ALTER TABLE promo_codes ADD CONSTRAINT fk_promo_codes_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE carts ADD CONSTRAINT fk_carts_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE carts ADD CONSTRAINT fk_carts_promo_code_id FOREIGN KEY (promo_code_id) REFERENCES promo_codes (id) ON DELETE SET NULL;
ALTER TABLE cart_items ADD CONSTRAINT fk_cart_items_cart_id FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE;
ALTER TABLE cart_items ADD CONSTRAINT fk_cart_items_sku_id FOREIGN KEY (sku_id) REFERENCES skus (id) ON DELETE RESTRICT;
ALTER TABLE orders ADD CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE orders ADD CONSTRAINT fk_orders_cart_id FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE SET NULL;
ALTER TABLE orders ADD CONSTRAINT fk_orders_promo_code_id FOREIGN KEY (promo_code_id) REFERENCES promo_codes (id) ON DELETE SET NULL;
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT;
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_sku_id FOREIGN KEY (sku_id) REFERENCES skus (id) ON DELETE RESTRICT;
ALTER TABLE order_status_history ADD CONSTRAINT fk_order_status_history_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE order_status_history ADD CONSTRAINT fk_order_status_history_changed_by FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE stock_reservations ADD CONSTRAINT fk_stock_reservations_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE stock_reservations ADD CONSTRAINT fk_stock_reservations_cart_id FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE SET NULL;
ALTER TABLE stock_reservations ADD CONSTRAINT fk_stock_reservations_sku_id FOREIGN KEY (sku_id) REFERENCES skus (id) ON DELETE RESTRICT;
ALTER TABLE payment_attempts ADD CONSTRAINT fk_payment_attempts_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT;
ALTER TABLE refunds ADD CONSTRAINT fk_refunds_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT;
ALTER TABLE refunds ADD CONSTRAINT fk_refunds_payment_attempt_id FOREIGN KEY (payment_attempt_id) REFERENCES payment_attempts (id) ON DELETE SET NULL;
ALTER TABLE refunds ADD CONSTRAINT fk_refunds_processed_by FOREIGN KEY (processed_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE return_requests ADD CONSTRAINT fk_return_requests_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT;
ALTER TABLE return_requests ADD CONSTRAINT fk_return_requests_order_item_id FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE RESTRICT;
ALTER TABLE return_requests ADD CONSTRAINT fk_return_requests_requested_by FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE return_requests ADD CONSTRAINT fk_return_requests_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE order_tracking ADD CONSTRAINT fk_order_tracking_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- Indexes
CREATE UNIQUE INDEX idx_users_email ON users (email);
CREATE UNIQUE INDEX idx_roles_name ON roles (name);
CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);
CREATE INDEX idx_addresses_user_id ON addresses (user_id);
CREATE INDEX idx_addresses_pin_code ON addresses (pin_code);
CREATE UNIQUE INDEX idx_serviceable_pin_codes_pin_code ON serviceable_pin_codes (pin_code);
CREATE INDEX idx_serviceable_pin_codes_is_active ON serviceable_pin_codes (is_active);
CREATE UNIQUE INDEX idx_categories_slug ON categories (slug);
CREATE INDEX idx_categories_parent_id ON categories (parent_id);
CREATE UNIQUE INDEX idx_brands_slug ON brands (slug);
CREATE UNIQUE INDEX idx_products_slug ON products (slug);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_brand_id ON products (brand_id);
CREATE INDEX idx_products_is_active ON products (is_active);
CREATE INDEX idx_products_average_rating ON products (average_rating);
CREATE INDEX idx_products_attributes_gin ON products (attributes);
CREATE INDEX idx_product_images_product_id ON product_images (product_id);
CREATE UNIQUE INDEX idx_skus_sku_code ON skus (sku_code);
CREATE INDEX idx_skus_product_id ON skus (product_id);
CREATE INDEX idx_skus_is_active ON skus (is_active);
CREATE UNIQUE INDEX idx_promo_codes_code ON promo_codes (code);
CREATE INDEX idx_promo_codes_is_active ON promo_codes (is_active);
CREATE INDEX idx_promo_codes_expires_at ON promo_codes (expires_at);
CREATE INDEX idx_carts_user_id ON carts (user_id);
CREATE INDEX idx_carts_status ON carts (status);
CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX idx_cart_items_sku_id ON cart_items (sku_id);
CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE UNIQUE INDEX idx_orders_order_number ON orders (order_number);
CREATE INDEX idx_orders_current_status ON orders (current_status);
CREATE INDEX idx_orders_created_at ON orders (created_at);
CREATE INDEX idx_orders_pin_code ON orders (pin_code);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_sku_id ON order_items (sku_id);
CREATE INDEX idx_order_status_history_order_id ON order_status_history (order_id);
CREATE INDEX idx_order_status_history_created_at ON order_status_history (created_at);
CREATE INDEX idx_stock_reservations_sku_id ON stock_reservations (sku_id);
CREATE INDEX idx_stock_reservations_order_id ON stock_reservations (order_id);
CREATE INDEX idx_stock_reservations_status ON stock_reservations (status);
CREATE INDEX idx_stock_reservations_expires_at ON stock_reservations (expires_at);
CREATE INDEX idx_payment_attempts_order_id ON payment_attempts (order_id);
CREATE INDEX idx_payment_attempts_status ON payment_attempts (status);
CREATE INDEX idx_payment_attempts_provider_reference ON payment_attempts (provider_reference);
CREATE INDEX idx_refunds_order_id ON refunds (order_id);
CREATE INDEX idx_refunds_payment_attempt_id ON refunds (payment_attempt_id);
CREATE INDEX idx_refunds_status ON refunds (status);
CREATE INDEX idx_return_requests_order_id ON return_requests (order_id);
CREATE INDEX idx_return_requests_order_item_id ON return_requests (order_item_id);
CREATE INDEX idx_return_requests_status ON return_requests (status);
CREATE INDEX idx_return_requests_requested_by ON return_requests (requested_by);
CREATE INDEX idx_order_tracking_order_id ON order_tracking (order_id);
CREATE INDEX idx_order_tracking_occurred_at ON order_tracking (occurred_at);
CREATE INDEX idx_notifications_user_id ON notifications (user_id);
CREATE INDEX idx_notifications_is_read ON notifications (is_read);
CREATE INDEX idx_notifications_created_at ON notifications (created_at);
CREATE INDEX idx_notifications_guest_email ON notifications (guest_email);
